apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: gatekeeper
  namespace: isidro
spec:
  template:
    spec:
      selector:
        app: gatekeeper
      ports:
      - name: api
        protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: mattermost
  namespace: mattermost
spec:
  template:
    spec:
      selector:
        app.kubernetes.io/name: mattermost-team-edition
      ports:
      - name: web
        protocol: TCP
        port: 8065
        targetPort: 8065